# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the entire project into the container
COPY . /app

# Install the required Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the default Flask port inside the container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP="docminer/app.py"

# Run the application
CMD ["python", "docminer/app.py"]
